name: Format (clang-format)

on:
    push:
        branches:
            - 'master'
    pull_request:
        paths:
            - '**.h'
            - '**.cpp'
            - '**.c'

jobs:
    clang-format:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}

            - name: Set up clang-format
              run: |
                  wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
                  sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main"
                  sudo apt install clang-format-17

            - name: Run clang-format
              run: |
                  which clang-format-17
                  clang-format-17 -i src/*.cpp src/*.h

            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: Apply clang-format changes
